export const generalNamesInSelectedLanguage = {
  search: '',
  deleteButtonInfo: '',
  updateButtonInfo: '',
  seeDrawing: '',
  seeHistory: '',
  operationAddSuccessStatusMessage: '',
  operationAddFailerStatusMessage: '',
  operationUpdateSuccessStatusMessage: '',
  operationUpdateFailerStatusMessage: '',
  operationDeleteSuccessStatusMessage: '',
  operationDeleteFailerStatusMessage: '',
  name: '',
  code: ''
};

export const generalUserNames = {
  partnerCode: '',
  partnerCompanyName: '',
  addNewBusinessPartner: '',
  addNewUser: '',
  fullName: '',
  email: '',
  changePassword: '',
  blockUser: '',
  unblockUser: '',
  businessPartnerOrders: '',
  userStatusBlocked: '',
  userStatusActive: '',
  userHasBennBlockedMessage: '',
  userHasBeenUnblockedMessage: '',
  admins: '',
  editors: '',

};

export const orderNames = {
  orderNumber: '',
  businessPartner: '',
  creator: '',
  index: '',
  date: '',
  createNewOrder: '',
  submitButtonNext: '',
  ChangeMaterialButtonInfo: '',
  ConfirmMaterial: '',
  ChangePartner: '',
  ConfirmPartner: '',
  ChangeProduct: '',
  ConfirmProduct: '',
  submitOrder: '',
  updateOrder: '',
  canNotFindProductForGivenParameters: '',
  orderAddSuccess: '',
  orderAddFailer: '',
  orderUpdateSuccess: '',
  orderUpdateFailer: '',
  orderDeleteSuccess: '',
  orderDeleteFailer: '',
  choosingOptionFromListIsRequires: '',
  choosingAndConfrimPartnerIsRequired: '',
  choosingAndConfirmProductIsRequired: '',
  choosingAndConfirmMaterialIsRequired: '',
  changeDrawingParameters: '',
  yourCommentToOrder: '',
  businessPartnerName: 'Nazwa Parnera Handlowego',
  businessPartners: 'Partne Handlowy',
  productType: 'Typ Produktu',
  productTop: 'Wykończenie Góry',
  productBottom: 'Wykończenie Dna',
  pressButtonToChooseProductByDrawing: 'naciśnij przycisk aby wybrać product na podstawie rysunku',
  chooseProductByDrawingButtonDescription: 'Wybierz Product klikając na rysunek',
  chooseProductByParameters: ' Wybierz produkt określając parametry produktu',
  productMaterial: 'Materiał Produktu',
};

export const drawingTableFormNames = {
  workingTemperature: '',
  antielectrostatic: '',
  workingSide: '',
  workingSideExternal: '',
  workingSideInternal: '',
  material: '',
};
